# Generated by Django 3.0.6 on 2021-03-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
